version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: samanyudu_db
    restart: always
    environment:
      POSTGRES_USER: samanyudu_user
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: samanyudu_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: samanyudu_app
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://samanyudu_user:your_secure_password@db:5432/samanyudu_db
      - USE_LOCAL=false
      - PORT=5000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=samanyudutvapp@gmail.com
      - SMTP_PASS=xfngqxwbsbisniye
      - SMTP_FROM=samanyudutvapp@gmail.com
      - MESSAGE_CENTRAL_CUSTOMER_ID=C-16D561181AAD471
      - TWO_FACTOR_API_KEY=4c4fdf41-1ae2-11f1-bcb0-0200cd936042
      - CLOUDFLARE_ACCOUNT_ID=dae1571f117c981c9d2b238bc07c6145
      - R2_ACCESS_KEY_ID=585a86e0e14f883f6b96808fe24227bb
      - R2_SECRET_ACCESS_KEY=775e510035de56cc3ed261a6c9bfc067c4cf1e51559866ecc15d591190f6f3da
      - R2_BUCKET_NAME=samanyudu-media
      - R2_PUBLIC_DOMAIN=pub-575580133514441ab6836d7e0cba0300.r2.dev
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
